CREATE TABLE IM_B_TASK_INFO(
ID BIGINT(20) NOT NULL AUTO_INCREMENT,
TYPE VARCHAR(10),
NAME VARCHAR(100),
CONTENT TEXT,
ICON_ADDRESS VARCHAR(100),
STAR_LEVEL BIGINT(20),
STAR_PROFIT BIGINT(20),
TIME_LENGTH VARCHAR(10),
STATUS VARCHAR(10),
AVAILABLE_STOCK BIGINT(20),
PERSION_AVAILABLE_STOCK BIGINT(20),
COUNT BIGINT(20),
CATEGORY VARCHAR(10),
CREATE_TIME DATE,
UPDATE_TIME DATE,
PRIMARY KEY(ID)
);

CREATE TABLE IM_B_TASK_MUTEX(
ID BIGINT(20) NOT NULL AUTO_INCREMENT,
TASK_FIRST_ID BIGINT(20) NOT NULL,
TASK_SECOND_ID BIGINT(20) NOT NULL,
CREATE_TIME DATE,
UPDATE_TIME DATE,
PRIMARY KEY(ID)
);

CREATE TABLE IM_B_GOODS_INFO(
ID BIGINT(20) NOT NULL AUTO_INCREMENT,
TYPE VARCHAR(10),
CATEGORY VARCHAR(10),
NAME VARCHAR(100),
STAR_NUMBER BIGINT(20),
DESCRIPTION TEXT,
STAR_LEVEL BIGINT(20),
ICON_ADDRESS VARCHAR(100),
STATUS VARCHAR(10),
COUNT BIGINT(20),
AVAILABLE_STOCK BIGINT(20),
CREATE_TIME DATE,
UPDATE_TIME DATE,
PRIMARY KEY(ID)
);

CREATE TABLE IM_B_NOTICE_INFO(
ID BIGINT(20) NOT NULL AUTO_INCREMENT,
TITLE VARCHAR(100),
CONTENT TEXT,
ICON_ADDRESS VARCHAR(100),
STATUS VARCHAR(10),
CREATE_TIME DATE,
UPDATE_TIME DATE,
PRIMARY KEY(ID)
);

CREATE TABLE IM_B_HONOR_TITLE(
ID BIGINT(20) NOT NULL AUTO_INCREMENT,
TITLE VARCHAR(100),
STAR_NUMBER BIGINT(20),
CREATE_TIME DATE,
UPDATE_TIME DATE,
PRIMARY KEY(ID)
);

CREATE TABLE IM_D_RECIVE_TASK(
ID BIGINT(20) NOT NULL AUTO_INCREMENT,
TASK_ID BIGINT(20) NOT NULL,
NAME VARCHAR(100),
CONTENT TEXT,
ACT_STAR_NUMBER BIGINT(20),
PRE_STAR_NUMBER BIGINT(20),
STATUS VARCHAR(10),
TRANS_ID BIGINT(20) NOT NULL,
START_TIME DATE,
EXPECTED_TIME DATE,
FINISHED_TIME DATE,
CREATE_TIME DATE,
UPDATE_TIME DATE,
PRIMARY KEY(ID)
);

CREATE TABLE IM_D_TRANS_RECORD(
ID BIGINT(20) NOT NULL AUTO_INCREMENT,
USERNAME VARCHAR(20),
STAR_NUMBER BIGINT(20),
STATUS VARCHAR(10),
START_TIME DATE,
FINISHED_TIME DATE,
CREATE_TIME DATE,
UPDATE_TIME DATE,
PRIMARY KEY(ID)
);

CREATE TABLE IM_D_SHOPPING(
ID BIGINT(20) NOT NULL AUTO_INCREMENT,
USERNAME VARCHAR(20),
GOODS_ID BIGINT(20) NOT NULL,
NAME VARCHAR(100),
CONTENT TEXT,
STAR_NUMBER BIGINT(20),
STATUS VARCHAR(10),
TRANS_ID BIGINT(20) NOT NULL,
START_TIME DATE,
FINISH_TIME DATE,
CREATE_TIME DATE,
UPDATE_TIME DATE,
PRIMARY KEY(ID)
);

CREATE TABLE IM_D_USER_INFO(
ID BIGINT(20) NOT NULL AUTO_INCREMENT,
USER_NAME VARCHAR(20),
NICK_NAME VARCHAR(100),
USER_NAME_CN VARCHAR(10),
PASSWORD VARCHAR(100),
WX_OPEN_ID VARCHAR(100),
AVAILABLE_STAR BIGINT(20),
EMAIL_ADDRESS VARCHAR(100),
FREEZE_STAR BIGINT(20),
HISTORY_STAR BIGINT(20),
GROUP_ID BIGINT(20) NOT NULL,
GROUP_NAME VARCHAR(100),
HONOR_TITLE VARCHAR(20),
UM VARCHAR(20),
CREATE_TIME DATE,
UPDATE_TIME DATE,
PRIMARY KEY(ID)
);

CREATE TABLE IM_D_SUBMISSIONS(
ID BIGINT(20) NOT NULL AUTO_INCREMENT,
RECEIVE_TASK_ID BIGINT(20) NOT NULL,
FILE_ADDRESS VARCHAR(100),
CREATE_TIME DATE,
UPDATE_TIME DATE,
PRIMARY KEY(ID)
);